### ISSUE TITLE
[ICON REQUEST]: Perforce

### ISSUE THREAD

**Issue by luca-drf** [devicons/devicon#1135]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

After Git and SVN, Perforce is probably one of the most widely adopted commercial VCS in the industry (especially gaming and semiconductors)

### Links and sources

Web:
- [Home](https://www.perforce.com/)
- [Wikipedia](https://en.wikipedia.org/wiki/Perforce)

Icon resources:
- [Simple Icons SVG](https://simpleicons.org/icons/perforce.svg)
- [LogoDix](https://logodix.com/logos/2011445)

**Comment by Snailedlt** [comment]
@kilian-paquier @luca-drf 
As far as I can tell Perforce (the product) has been renamed to Helix Core now. Perforce is still being used as the company name, but since we only accept products, and not company logos, I can't accept your PR, nor this issue. Let me know if I'm wrong, and perforce is also a product logo, and I will open up the issue again.

Source:
https://www.perforce.com/blog/what-is-perforce
> Perforce Software is a leading provider of development and DevOps solutions. This includes the original Perforce version management system, now called Helix Core, as well as dynamic development, intelligent testing, risk management, and boundaryless collaboration solutions.

**Comment by kilian-paquier** [comment]
Yep, I confirm after a light search.

**Comment by gagan-suie** [comment]
gotcha! ill make a request for Helix Core
