### ISSUE TITLE
[ICON REQUEST]: Cassandra

### ISSUE THREAD

**Issue by saveriogzz** [devicons/devicon#1192]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cassandra is a NoSQL distributed database

### Links and sources

https://commons.wikimedia.org/wiki/File:Apache-cassandra-icon.png
https://icon-icons.com/search/icons/cassandra
https://iconscout.com/icon/cassandra

### Preview
![Cassandra_logo](https://user-images.githubusercontent.com/42075938/169969485-31377c58-7de7-4633-9770-99a11f8119c9.svg)

**Comment by Snailedlt** [comment]
Official logos can be found here: https://www.apache.org/logos/#cassandra

I think these are the ones we should use:

## cassandra-original-wordmark.svg
https://svn.apache.org/repos/asf/comdev/project-logos/originals/cassandra-2.svg
![](https://svn.apache.org/repos/asf/comdev/project-logos/originals/cassandra-2.svg)

## cassandra-original.svg
https://svn.apache.org/repos/asf/comdev/project-logos/originals/cassandra-4.svg
![](https://svn.apache.org/repos/asf/comdev/project-logos/originals/cassandra-4.svg)

**Comment by saveriogzz** [comment]
Great job @Snailedlt ! How can I help you merging it?

**Comment by Snailedlt** [comment]
Hi @saveriogzz 
I'm glad you're following up on this
Sorry for the late response. Been busy lately since we're only two maintainers atm, and both of us have had busy weeks :)

Anyways, if you want to get it merged as fast as possible, the best way would be to make a PR with the new icons like so -> [Overview-on-Submitting-Icons](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)

We are planning on making a new release of devicon soonᵀᴹ, probably sometime in November or early December.

**Comment by Snailedlt** [comment]
Official icons: https://svn.apache.org/repos/asf/cassandra/logo/

Lots of versions to pick from. Here's the .svg versions, but there's also .ai, .pdf and .eps files available at the link above
![](https://svn.apache.org/repos/asf/cassandra/logo/cassandra.svg)

**Comment by Snailedlt** [comment]
@lunatic-fox Agreed

**Comment by lunatic-fox** [comment]
Done!

**Comment by saveriogzz** [comment]
Hey folks! Thanks a lot for your contributions 🎉 
Will these changes be merged to master? Thanks!
