### ISSUE TITLE
[ICON REQUEST]: (Oh My) ZSH

### ISSUE THREAD

**Issue by SIMULATAN** [devicons/devicon#1264]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

ZSH is quite a popular shell, used by many developers, often in conjunction with Oh My ZSH (147k GitHub stars)

### Links and sources

ZSH (shell itself): https://commons.wikimedia.org/wiki/File:Z_Shell_Logo_Color_Vertical.svg
Oh My ZSH (configuration framework): https://ohmyz.sh/img/ohmyzsh-original-logo.svg

**Comment by SIMULATAN** [comment]
It would be great to have both, but I think that OMZ is definitely more important, since it is the one actually doing the "magic"

**Comment by jeremyxwing** [comment]
I wonder if more people would be familiar with ZSH as a common default vs Oh My ZSH as a plugin for enthusiasts. I would assume anyone using a ZSH icon is also indicating Oh My ZSH. The Oh My ZSH icon might also not look great when it's small with all the people in it.

**Comment by SIMULATAN** [comment]
OMZ isn't really a plugin for enthusiastics, but rather, it's mostly the reason for using ZSH in the first place.

**Comment by jeremyxwing** [comment]
@SIMULATAN You're not wrong! 🤘

**Comment by Snailedlt** [comment]
@SIMULATAN Nice one. Could you make a separate request for ZSH too?

Like it's explained here, every icon should have it's own separate issue -> https://github.com/devicons/devicon/wiki/Requesting-an-Icon

**Comment by BenSouchet** [comment]
And for info the ZSH official logo : https://github.com/Zsh-art/logo
I get the link from the news page of the ZSH org: https://zsh.sourceforge.io/News/

**Comment by Snailedlt** [comment]
I wonder which icon they would prefer us to use for the original icon, since they have two different ones that both seem pretty official. I'd assume the one with color is the one to use, but can't find a SVG version of it.

![logo with color](https://ohmyzsh.s3.amazonaws.com/omz-ansi-github.png)
![logo without color](https://ohmyz.sh/img/ohmyzsh-original-logo.svg)

**Comment by BenSouchet** [comment]
@Snailedlt In my PR I use the one provided by the creator of Oh My Zsh here : https://github.com/ohmyzsh/ohmyzsh/issues/11019#issuecomment-1179648449

The retro one with color isn't the main one, it's a retro variant they created after.

**Comment by Snailedlt** [comment]
@BenSouchet Hmm okey, both seem to be official, and the new retro one is being called their logo in some of their commit messages. I guess we can ask them directly which one they prefer :)

**Comment by BenSouchet** [comment]
@Snailedlt Like I said, the creator of the tool give the the SVG logo file, why do you want to ask, or use the retro one? Since it's more complicated and also not possible to use in the devicon font.

You can still ask but no one will ever vectorize the retro one, it's terminal "ascii" art.

**Comment by Snailedlt** [comment]
@mcornella @robbyrussell 
Hi! Any chance you can shed some light on what icon `Oh My Zsh` thinks should be included here?

**Comment by Snailedlt** [comment]
a.k.a. which one do you prefer, and which one is the official one?

**Comment by BenSouchet** [comment]
Nice spam...

**Comment by mcornella** [comment]
@Snailedlt please use the vectorized old logo. The ascii art variant is not supposed to be used as the main one.

**Comment by Snailedlt** [comment]
Great, thank you for your quick response @mcornella 💯

**Comment by BenSouchet** [comment]
@Snailedlt I don't want to be rude but you need to stop being so picky, you want to do things good but when you already have an anwser, you can see the logo used in the website, you have an issue answered by the creator of the tool with the SVG file, why in hell do you want to ping people ??

By doing this you devalue the work of people like me creating PRs.

**Comment by Snailedlt** [comment]
@BenSouchet 
First of all I'm sorry if I was rude. That's never been my intention.

Imo being picky is a good thing though. It prevents bugs, typos, misunderstandings and a bunch of other problems that would otherwise need to be fixed afterwards. Overall it saves time, and improves quality.

I see you answered already, but no offense, your answer is not an official one. There have been times before, where we thought we picked the right icon, only to later figure out it wasn't. I just wanted to make sure we picked the correct one, so we didn't have to redo it.

**Comment by BenSouchet** [comment]
@Snailedlt 
After all the elements that was listed above I can't believe that a doubt remained on the icon to use, in my opinion I think it's more about your ego, you are picky (way too much) to show that you have something to say.

My opinion :
On each PR you look for things to say. Having relevant feedback is good but when it is more on the subjective side it has no place (in my opinion) in a PR thread.

I think you will realize that if you want people to continue to actively participate in open source projects you have to be cooler, things will not be always perfect for you, and it's okay / normal.

I think you have a lot of motivation for Devicon, but you can't always convince people to see things the way you do.

Last message for me in this thread, I think we can agree that we won't find a common ground on the topic and I don't want to spam.
Have a great day!

**Comment by Snailedlt** [comment]
@BenSouchet I think you're right about me being too picky sometimes (or maybe often). I do still think it was a good idea to ask though. It took what, like 1min to ask? and we got a concrete answer from the maintainer of the project. Now there's no doubt at all which icon we should use, and there's no need for a discussion.

You say subjective things have no say in the matter. Isn't that another reason to get an answer from the creators of the icon?

I dunno, I feel my decision was right. I do agree it can be considered spam, and picky, but I still think it was the right thing to do, and I think this is an overreaction on your part.

Now as for the more general message of your comment, I agree that I'm a bit too picky often times, and I'll work on that. Thank you for letting me know, even though I think you should have brought it up in a more respectful manner. 

I hope this doesn't discourage you from contributing in the future, since I think you're a great asset to the repo :)
Have a great day you too! 💯 

**PS:** if you want to have a chat in dm so as to not spam here, you can contact me on discord `Snailed lt#3563`

**Comment by BenSouchet** [comment]
@SIMULATAN Please don't close the issue until a new version of Devicon as been release. So we can keep track of element added and others people can see the icon is in develop but no yet available on the current version.
@Snailedlt can you re-open it.

**Comment by SIMULATAN** [comment]
Implemented in b9023a5a309bdd4df0cc7ce093241fe1a2a1afc3, but unreleased right now.

**Comment by SIMULATAN** [comment]
Sorry for closing it too early - I'm not on my computer and just saw the PR was merged so I figured I'd close it, sorry for not checking before taking action :/

**Comment by Snailedlt** [comment]
No worries :)

**Comment by mcornella** [comment]
Just for the record, it was not an issue to ask us @Snailedlt. And thanks @SIMULATAN for taking care of this :)

**Comment by Snailedlt** [comment]
Thank you @mcornella :heart:

The icon has been merged into develop now, and I think a new release is coming soon
