### ISSUE TITLE
[ICON REQUEST]: ruby_on_rails

### ISSUE THREAD

**Issue by HeavyArms0511** [devicons/devicon#1375]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Trying to use the cheat sheet for the ruby_on_rails and its not working.

### Links and sources

http://vorillaz.github.io/devicons/#/cheat

### Additional information

I attempt to use the icon for ruby on rails using the text 'ruby_on_rails' and it does not work.  No idea why all the other icons I have picked worked fine.

**Comment by BenSouchet** [comment]
Hi, after looking up it seems that the name to use is "rails" (or if the altnames are working "rubyonrails").
@Snailedlt Is it normal that the altnames aren't used for the searchbar on the devicon.dev website (not implemented ?).

So it's not a missing icon put I agree that it's an issue that when I type "ruby" on the devicon.dev website I can't find  the icon of **Ruby on Rails**.

**Comment by Snailedlt** [comment]
There hasn't been a release since altnames were added, so they are still only on the develop branch. Once the develop branch has been merged into master and there's been a new release, altnames will be used in the searchbar.

So in short, this issue should be fixed [here](https://github.com/devicons/devicon/blob/develop/devicon.json#L6030-L6033)
