### ISSUE TITLE
[FEATURE REQUEST] Add the appropriate labels automatically

### ISSUE THREAD

**Issue by Panquesito7** [devicons/devicon#1399]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

It would be awesome if a GitHub Actions workflow detected if a new directory has been made under the `icons` folder, and added the appropriate labels. The `bot:peek` label could be added too if it matches all the requirements and standards (it could take a bit long time to code, though).

What do you think about this? 🙂

**Comment by Snailedlt** [comment]
Agreed, though I think we could make it even easier and just have the bot check the PR title. If it starts with `new icon` or `update icon`, we automatically add the `feature:icon` label

We might be able to use this :) 
https://github.com/actions/labeler

I haven't checked it out thoroughly, but hopefully it has something we can use. Otherwise it shouldn't be too hard making our own action

**Comment by Snailedlt** [comment]
For ![][~feature:icon] and ![][~enhancement] labels we can just add `&labels=feature:icon` and `&labels=enhancement` to the end of the PR. 
ref: https://github.com/isaacs/github/issues/1252#issuecomment-638148723
I'll make a PR on this in a few min

As for the bot:peek label, it would require more work. I think we should move that to a different issue, so we can keep the scope of this one as small as possible.

[~feature:icon]: https://img.shields.io/badge/-feature:icon-6cc43c.svg
[~enhancement]: https://img.shields.io/badge/-enhancement-84b6eb.svg
