### ISSUE TITLE
[FEATURE REQUEST] <feature name>

### ISSUE THREAD

**Issue by kumarmeet** [devicons/devicon#1598]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

RESTApi icon should be also in the list. It would be good to have if this in bucket of devicons collections.

**Comment by PantheraRed** [comment]
Hello @kumarmeet, if this is suppose to be an icon request please follow this [wiki](https://github.com/devicons/devicon/wiki/Requesting-an-Icon) on how to request icons. If it is intended to be some sort of feature please clarify title of your feature in issue's title and describe a more about your feature.

**Comment by kumarmeet** [comment]
Title: RestApi icon request

Description: As we know RESTApi is also a technical / IT part we could need that RESTApi icon. Actually when i was implementing the devicons on my portfolio website then i need to showcase my skills on that so i found graphql but i search restapi on devicon it was not there.  

Reference link: https://icons8.com/icons/set/rest-api

**Comment by lunatic-fox** [comment]
Hello there!

Thank you for open this issue, but I think REST API doesn't fit even in special cases, most because it doesn't have any official icon.

It's similar to HTTP and SOAP, two protocols that don't have a proper icon. In other hand, technologies used in REST API and those other protocols does have their own icons, like: JSON, XML, HTML, JavaScript, PHP, Python and more.

Wish for the best!

**Comment by Snailedlt** [comment]
@kumarmeet Thank you for opening an issue.
However, like @lunatic-fox explained, we won't be adding RESTapi to devicon since it doesn't have an official icon (atleast afaik).

For that reason I'll close this PR.

If you end up finding an official logo down the road, let me know so we can re-open this issue :)
