### ISSUE TITLE
OpenAI

### ISSUE THREAD

**Issue by gagan-suie** [devicons/devicon#1755]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

Because it's the best dev tool ever

### Links and sources

https://openai.com/brand

**Comment by kilianpaquier** [comment]
Hello @gagan-suie, thank you for your issue !

Sadly OpenAI is the company, not the tool. So we won’t be able (outside of a potential exception) to add it to devicon according to accepted icons section (https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#what-icons-do-we-accept).

However, feel free to update your PR with the official branding for GPT, which is the tool. But I don’t know if there’s a logo for it 🤔.

Still, @Snailedlt, @Panquesito7, what do you think ?

**Comment by Snailedlt** [comment]
I agree with @kilianpaquier.
Since OpenAI is a company, and not a technology, it won't be accepted. If there are official icons for the dev tools (like GPT-4 or GPT-3) you can suggest those :)

For more info on which icons we accept, and why there are some company icons in the logo-set already, read this: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F
