### ISSUE TITLE
[OTHER] Is devicons still being worked on?

### ISSUE THREAD

**Issue by marcusleonas** [devicons/devicon#1967]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

There are tons of open icon requests but no new updates? I see that you've added some to the `develop` branch but the last time the icons were updated in master was last year.

**Comment by canaleal** [comment]
Hey @flvffywvffy, thank you for reaching out and for your keen interest in the project. We truly appreciate your patience and support.

We are actively working on the project, and I'm excited to share that a new release is on the horizon. Our team is currently focused on perfecting the finer details, particularly with respect to font display and overall quality. Please stay tuned, as we're ironing out the last few kinks and anticipate rolling out the updated collection very soon.

**Comment by Snailedlt** [comment]
Also worth noting that after the next release we'll be focusing on moving to a trunk-based development strategy, which will significantly decrease complexity, improve our agility and increase the frequency of releases in the future.

**Comment by davidleger95** [comment]
Hello! Just wondering if there's an ETA for the next release. Thanks!

**Comment by Snailedlt** [comment]
@davidleger95 Hard to say since new stuff keep popping up. I think we're done with all the workflow related stuff, so we should be able to make a release once all of the issues outlined in this comment are fixed: https://github.com/devicons/devicon/pull/1998#issuecomment-1807542194

Current progress:
![image](https://github.com/devicons/devicon/assets/43886029/90213326-5b4a-4dae-96a8-576420fe08a0)

**Comment by canaleal** [comment]
Closing ticket as it's now outdated.
