### ISSUE TITLE
Python SVG Icons Not Working

### ISSUE THREAD

**Issue by dylanbuchi** [devicons/devicon#326]
Hello, so the SVG versions of the Python icon are not working. I tested all of them and they aren't showing in my browser.

**Comment by amacado** [comment]
I can confirm there is an error with the svg versions of `python-original` and `python-original-wordmark`.
This is actually caused by our method of showing the svg-code based on the original svg file in the `icons/` dir. In this case it will remove the following lines which then leads to an error when displaying the icon:
```
[...]
<linearGradient id="a" gradientUnits="userSpaceOnUse" x1="70.252" y1="1237.476" x2="170.659" y2="1151.089" gradientTransform="matrix(.563 0 0 -.568 -29.215 707.817)"><stop offset="0" stop-color="#5A9FD4"/><stop offset="1" stop-color="#306998"/></linearGradient>
[...]
<linearGradient id="b" gradientUnits="userSpaceOnUse" x1="209.474" y1="1098.811" x2="173.62" y2="1149.537" gradientTransform="matrix(.563 0 0 -.568 -29.215 707.817)"><stop offset="0" stop-color="#FFD43B"/><stop offset="1" stop-color="#FFE873"/></linearGradient>
[...]
<radialGradient id="c" cx="1825.678" cy="444.45" r="26.743" gradientTransform="matrix(0 -.24 -1.055 0 532.979 557.576)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#B8B8B8" stop-opacity=".498"/><stop offset="1" stop-color="#7F7F7F" stop-opacity="0"/></radialGradient>
[...]
```
Used by this `<path>` for displaying the svg
```
<path fill="url(#a) [...]
```

The fix can be probably found in this line of code:
https://github.com/devicons/devicon/blob/5b74e5ed66d52d3463a3a16149d919294d0ec740/assets/js/script.js#L110

**Comment by Thomas-Boi** [comment]
Is there anyway to fix this in the code base?

**Comment by amacado** [comment]
Yeh, should be possible.. I can remember I tried it some weeks ago but had not the time to complete it.. I will have a look at it
