### ISSUE TITLE
Icon request: VMWare

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#433]
### About the icon
VMWare is virtualization tool
### Links
https://www.vmware.com/
### Preview
![kisspng-logo-vmware-vsphere-vcenter-virtualization-it-аутсорсинг-it-outsourcing-Киев-5b62e2faa5be87 7897632215332072906789](https://user-images.githubusercontent.com/33158051/103466517-e19fdd80-4d13-11eb-9e31-c3ccaca9dd3d.jpg)

**Comment by amacado** [comment]
Adding vmware might need some discussion..

>Companies logo should not belong to repo UNLESS their logo is also their product's logo. Only the tools or languages created by those companies should be accepted.

see https://github.com/devicons/devicon/discussions/353

**Comment by Thomas-Boi** [comment]
I agree, VMware seems to refer to a specific company and not a product. I would suggest requesting for an icon of their products, which can be found [here](https://www.vmware.com/products/cloud-foundation.html)

**Comment by Thomas-Boi** [comment]
Actually, now that I think about it, we do have Amazon Web Services in our repo. When most people think of Amazon, they think of Amazon's cloud computing products (EC2, CloudWatch, EBS, etc...). It also make sense since you can't only use one Amazon product, it's usually a combination.

Since VMWare kinda fits the same format, I think we can make an exception to the "no company" rule. What do you think @amacado ?

**Comment by amacado** [comment]
@Thomas-Boi it's one of these edge cases. As you mentioned Amazon Web Services: From my point of view this can't be compared to vmware since the company behind Amazon Web Services is Amazon (and we would not add Amazon to our icons). Amazon Web Services can be seen as a own Product (even if it is more like a wrapper for multiple offers like EC2, S3,...). I don't think vmware can be seen as a product in the way we see it for aws. For now I would reject adding vmware but instead adding the products like Virtual Box (https://github.com/devicons/devicon/issues/436). If there are many people asking for vmware to be added we can reopen the discussion.

**Comment by Thomas-Boi** [comment]
@amacado That sounds like a good idea. I'm not too familiar with VmWare beside their Virtual Box so I thought it's similar to AWS. I'll go with your idea on this one
