### ISSUE TITLE
workflows on pull requests failing due to wrong `ref`

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#471]
Currently the bot:peek command failes (https://github.com/devicons/devicon/pull/217/checks?check_run_id=1671030442). I think this is because of the `ref: ${{ github.head_ref }}`

https://github.com/devicons/devicon/blob/develop/.github/workflows/peek_icons.yml#L13
```
ref: ${{ github.head_ref }}
```

It was merged in https://github.com/devicons/devicon/pull/460 and the problem will occur in the other workflow scripts as well I think. @Thomas-Boi what was the reason you changed this? :)

**Comment by Thomas-Boi** [comment]
Oh, that was because the checkout action was having changes from the develop branch AND the PR branch. I thought that it's probably a better idea to just limit the checkout to the PR branch, hence the [`github.head_ref`](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context). 

It seems like this would cause the checkout action to checkout the PR branch, which would not belong to us => It has no permission => Script would fail.

I will fix this and push it in a new commit asap.

**Comment by Thomas-Boi** [comment]
Created a test PR at #474

**Comment by amacado** [comment]
sure, just give me a hint when you're done :)

**Comment by amacado** [comment]
Fixed in https://github.com/devicons/devicon/pull/472
