### ISSUE TITLE
Replace raw.githubusercontent.com in devicon.dev with CDN (nosniff header problem)

### ISSUE THREAD

**Issue by d3cline** [devicons/devicon#572]
The CSS link on the demo site is broken due to mime type. 
![image](https://user-images.githubusercontent.com/77483/115941052-03f36d80-a461-11eb-9d6b-dfb5f1c8082b.png)
link needs to be updated to another CDN such as,
`https://cdn.jsdelivr.net/gh/devicons/devicon/devicon.min.css`

**Comment by Panquesito7** [comment]
Are you sure it's failing? I'm not receiving any error here.
![Inspect: console](https://user-images.githubusercontent.com/51391473/115942122-43748680-a46e-11eb-9a3a-a57f1cf0bd9f.png)

**Comment by amacado** [comment]
Hello @d3cline, thanks for pointing that out. It's true that some browsers (or settings) will block content which is requested from raw.githubusercontent.com. This is because of the `nosniff` header provided by github.

![image](https://user-images.githubusercontent.com/8781699/115954983-41550b00-a4f4-11eb-930d-dd2d2868f761.png)

This issue does not occur for every user (I don't have it either) but in some scenarios it will lead to the error you are describing. It probably can be resolved by using a CDN as deliverer of the files. When this is beeing fixed note that not only the `css` files are loaded via githubusercontent but also the `svg`.

![image](https://user-images.githubusercontent.com/8781699/115955059-b0cafa80-a4f4-11eb-88f7-d125c28c5acc.png)


See [this thread](https://stackoverflow.com/a/41309463/8271818) for more information about the topic.

**Comment by theblobscp** [comment]
If there were two prs that fix this, why is this still open

**Comment by amacado** [comment]
Yep, can be closed since it's done.
