### ISSUE TITLE
Icon request: Discord

### ISSUE THREAD

**Issue by Nahim-Diaz** [devicons/devicon#594]
### About the icon
Discord is a freeware voice chat instant messaging service
### Links
Discord: https://discord.com/

**Comment by Thomas-Boi** [comment]
Hi @Nahim-Diaz, can you change the Issue name so it shows "Discord" please?

On another topic, @Panquesito7 and @amacado what do you think? Does Discord belongs in our repo? Personally, I think it's a bit too generic to be count as a "programming" tool. On the other hand, Discord is being used in many websites and I think quite a few people would like it in the repo. I would say yes but I want to get your thoughts too.

**Comment by Nahim-Diaz** [comment]
Hi @Thomas-Boi , I think the discord icon appears on many websites that have communication channels there, also as a means of contact since many people are starting to use it as messaging (including programmers)

**Comment by amacado** [comment]
Based on https://github.com/devicons/devicon/discussions/353#discussioncomment-168838
>Tools that are too general should not be added. Special cases can be treated on a case-by-base basis, such as Slack or LinkedIn

I vote against adding `discord` to this project. It's a generic communication tool and not related to developing at all (unless you can prove otherwise). Sure it can be used by "developers" (but **every** tool can be used by developers). I don't see a direct relation between development and discord.

**Comment by Panquesito7** [comment]
I agree with @amacado: this icon doesn't actually fit for Devicons. You can use an SVG directly in the [Discord branding's](https://discord.com/branding) page. Thank you. 🙂
