### ISSUE TITLE
Bug Report: Arduino icon broken

### ISSUE THREAD

**Issue by justisGipson** [devicons/devicon#684]
### Bug
*Short description of the bug that you found. Provide images/code if applicable.*

Arduino icon doesn't render on main page
all 4 font versions never render
SVG versions do render on page

<img width="1230" alt="Screen Shot 2021-06-14 at 3 50 34 PM" src="https://user-images.githubusercontent.com/42194039/121951025-657cdd80-cd28-11eb-88c1-1aee5707c436.png">

### How to replicate the bug
*What should we do to replicate this bug.*
visit - https://devicon.dev/ and look at the arduino icon

### Possible Fixes/Solutions
*List any possible fixes/suggestions that you have in mind that could solve this issue.*

**Comment by justisGipson** [comment]
🤔 if this could be related to #656? I have no idea is this is the case or not

**Comment by amacado** [comment]
@justisGipson thanks for reporting. We're investigating on that!
I tried uploading and building the icons manually to see if there's any issue, but it looks alright.

![image](https://user-images.githubusercontent.com/8781699/121954847-814fa600-cd5f-11eb-9fc2-a1ee89f15844.png)

**Comment by Thomas-Boi** [comment]
That's strange.  I can't think of any reason why this is the case.

One thing to note is we did have issues with the `arduino` icon before when we upload it to icomoon. I'll keep investigating and see what's causing it.

**Comment by Thomas-Boi** [comment]
Bug: `arduino` was never added to the build list. I uploaded the `icomoon.json` from the latest build (`v2.12.0`) and there's no `arduino` icons. 

Reason: This is caused by GitHub's way of organizing PR and the build bot's recent upgrades.

Details:
- The build script will look through the past PRs until it encounter a PR matching the regexp `Release v`. This will encounter the PR marked by the arrow on page 3
![image](https://user-images.githubusercontent.com/43018778/122342410-74ff5080-cef9-11eb-9afc-f9ee7a9914d2.png)
- However, `arduino` was listed on page 4. Thus, the bot wouldn't have seen it
![image](https://user-images.githubusercontent.com/43018778/122342876-f35bf280-cef9-11eb-9db6-0e2bbea91a4e.png)

Fix:
- Ironically, the old build bot would have spotted this PR since it was in the `devicon.json` but wasn't added to the `icomoon.json`.
- Thus, the solution is changing the script so the bot will check both things. This will ensure we still get the updated icons AND weird edge cases such as these.

**Comment by Thomas-Boi** [comment]
For reference reason: the `arduino` icon will be available in the next release since that' when we will run the new build bot.
