### ISSUE TITLE
Feature Request: Label Issues that are in-progress/in-develop and Auto close issues on merge

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#754]
### Discussed in https://github.com/devicons/devicon/discussions/749

<div type='discussions-op-text'>

<sup>Originally posted by **TheFoxarmy** July 15, 2021</sup>
Will issues with PRs referencing them get closed automatically?
There are lots of open issues, could some of them be kicking around from old updates that are yet to be closed?
It might be a good idea to use one of those actions and if a PR references an issue, make it in-progress, and if it gets merged, close it automatically. If it already closes them, cool, but marking them in-progress would make it easier for people to choose which icons to do next.</div>

**Comment by theblobscp** [comment]
I agree with you, even though I barely understand you

**Comment by Thomas-Boi** [comment]
I would like to do something like this as well. While GitHub provides the ability to close PR automatically, a contributor would have no idea if the icon is currently in `develop` or is being reviewed.

There's [this action](https://github.com/devicons/devicon/issues/702) that we can use when an icon is merged into `develop`. Basically, when a PR is closed, we can label an associated issue with a certain label.

I think I'll work on this feature regardless of whether the auto-closing Issue works with commit message. It'll help either way.

**Comment by theblobscp** [comment]
Alright

**Comment by Snailedlt** [comment]
Any progress with this @Thomas-Boi?

**Comment by Thomas-Boi** [comment]
> Any progress with this @Thomas-Boi?

I'm starting to look into this once again. I have an idea in mind and it'll be laid out in a Feature Request

**Comment by Thomas-Boi** [comment]
I'll just do it here since this Issue is about this problem specifically.

I'm planning to make 2 extra bot:
- `in-develop-labeler`, which will be activated whenever a PR is merged into `develop`. It'll scan the PR's descriptions/linked issues and find any issues linked. It'll then apply an `in-develop` label (which we already have) to the Issues.
- `close-issues-bot`, which will close all the issues with the `in-develop` label. This will be triggered after the release build is merged from `develop` into `master`. I might make the trigger a bot command or just an if statement. We'll see

**Comment by Snailedlt** [comment]
> I'll just do it here since this Issue is about this problem specifically.
> 
> I'm planning to make 2 extra bot:
> 
> * `in-develop-labeler`, which will be activated whenever a PR is merged into `develop`. It'll scan the PR's descriptions/linked issues and find any issues linked. It'll then apply an `in-develop` label (which we already have) to the Issues.
> * `close-issues-bot`, which will close all the issues with the `in-develop` label. This will be triggered after the release build is merged from `develop` into `master`. I might make the trigger a bot command or just an if statement. We'll see

Sounds good to me. Just make sure it doesn't add the `in-develop` label to any referenced issue, since you might want to reference an issue without closing it. It should seearch for the `close` keywords [listed here](https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request#closing-issues), followed by `#issueNumber`.

Take the following sample into consideration:
There's an issue regarding updating the styling of CONTRIBUTING.md. Let's call this issue `#1`
You're fixing an issue with some minor typos, or add a section in that same file. We can call this one issue `#2`
Now you might want to let the reviewer(s) know that you know the styling in `#2` isn't on point, but it should rather be fixed in `#1` for whatever reason.
In this case we don't want `#1` to be closed, but we simply want to reference it to let the reviewers know that this issue `relates` to the one you're fixing.

Hope this clarifies my point. If not, feel free to ask me about it, and I'll try to further clarify :)

**Comment by Thomas-Boi** [comment]
I think that make sense. Sometimes, I'd make a PR that fixes a small issue but then reference a bigger issue that I'd work on later. I'm even thinking of changing the template so that it's explicit what issues should be closed when the PR is merged into `master`.
