### ISSUE TITLE
Feature Request: [Blockchain Development Icons]

### ISSUE THREAD

**Issue by iamrobins** [devicons/devicon#758]
### Suggested Feature
Create blockchain development icons, Examples - A Blockchain default icon, Bitcoin, Etherum, Dogecoin, and programming languages like Solidity and Vyper which are used in Blockchain app development.

### Why we should have this feature
Blockchain developers can use the icons from devicon repository.

**Comment by Thomas-Boi** [comment]
Hi @iamrobins,

I think this is a neat idea. However, I'm not sure how some of these crypto fits into the [definition of our repo](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#what-icons-do-we-accept). I can see Ethereum with their smart contracts or Graph with their querying platform fitting the repo. Same with smart contract programming languages. However, Bitcoin and Dogecoin for example are more general usage and not necessary a development tool.

I won't close the Issue since I think it's a valid feature. However, icon request of cryptos will be filtered such that it matches our standard.

**Comment by iamrobins** [comment]
Yeah I was also not sure about the coins as you said they falls in the general purpose category. You must filter them out 👍

**Comment by Thomas-Boi** [comment]
I'll close this for now. We'll take them as they come
