### ISSUE TITLE
Icon request: Corel Draw

### ISSUE THREAD

**Issue by Wilberson-Roberto** [devicons/devicon#867]
### About the icon

I need a icon of the Corel Draw for my status

### Links and sources

i have this image
![corel](https://user-images.githubusercontent.com/90524071/134730045-b0276e2f-ec6b-4ea3-82d6-3fe2af59eb5f.jpg)

Would it be possible to add this image to the devicon.dev database?
I need to add to my status in readme.md

i have this image in SVG on my repository
[Here](https://github.com/Wilberson-Roberto/Wilberson-Roberto/blob/main/img/coreldraw.svg)

**Comment by BenSouchet** [comment]
In my opinion this software suite isn't truly related to development, I know that the discussion https://github.com/devicons/devicon/discussions/353 is still open but I my opinion this this graphic design not development.

@Thomas-Boi @amacado What do you think?

**Comment by Wilberson-Roberto** [comment]
Thank's for you opinion @BenSouchet , I kind of wanted to also display my training in this area, because I have more than 8 years of experience, but I will remove my relationship with Graphic Design, because all I want now is to be a developer.

**Comment by amacado** [comment]
In general I agree with @BenSouchet. As our [guidelines ](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#requestingIcon) say:

>Devicon only accepts Icons of development languages and tools.
> Development refers to programming or programming-related jobs.

>Special Cases (see this discussion for more details)
Related fields like graphic designs or game development. Since many "development" jobs require people to know related fields, some softwares will be accepted in Devicon even though they aren't strictly "development tools".

Corel Draw is one of those special cases and I tend to not accept it in this repository (to sharpen the purpose of this project). See latest discussion #353.

**Comment by Thomas-Boi** [comment]
This one is a bit tough for me. We accepted brands like Photoshop and Inkscape because it's related to web development. I think CorelDRAW is pretty similar as well. However, the app is also not as well known as the above options so I don't know if adding it to the repo would be a good idea. I'm leaning towards no on this one due to this reason.

Perhaps you can create a font file specifically for this SVG yourself? Check out [this wiki](https://github.com/devicons/devicon/wiki/How-We-Create-The-Icons) where we explain how you can edit the font files using Icomoon. This way, you can add icons that aren't accepted in the repo on your own. You can also make your own font files as well.

**Comment by BenSouchet** [comment]
@Thomas-Boi Don't know for Inkscape but in photoshop you can code scripts, create and add plugins see the photoshop scripting doc here:
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-scripting-guide.pdf

**Comment by Wilberson-Roberto** [comment]
Thank's evryone, I’ll reorganize my portfolio.
