### ISSUE TITLE
Icon request: Express.js

### ISSUE THREAD

**Issue by WolfgangVing** [devicons/devicon#973]
### About the icon

A version for Night Theme

### Links and sources

Express official website: https://expressjs.com/ 
Express repository: https://github.com/expressjs/express

### Additional information

The icon should have a version for those who prefer Night Themes, since because the one available now will be difficult to.

**Comment by Thomas-Boi** [comment]
Hello @WolfgangVing,

Are you referring to the font icon or the SVG version? If it's the font icon, you can change the color using the CSS `color` attribute. As for the SVG version, you'll have to change the SVG color manually. This is because we want to avoid storing multiple versions of the same SVG where the color is the only one that's changed.

**Comment by WolfgangVing** [comment]
If someone is importing for another project that may be the case, but my case is that I'm only using for profile Readme. I made my readme with [profile-readme-generator](https://rahuldkjain.github.io/gh-profile-readme-generator/), I assume a lot of people have been using it too. Since I can't change the color or the SVG because have limited capabilities (the Readme Profile), I thought I would search whether the source used by the generator would have another version or not.

**Comment by Thomas-Boi** [comment]
After checking out the page, it seems like they are using our SVGs inside their `README.md` using `<img>` tags.
![image](https://user-images.githubusercontent.com/43018778/146840271-e1a47d99-5774-4401-a420-68f456ebe644.png)

Since they are only generating the Markdown, perhaps you can customized the icon to your liking when you need? For example, say I don't like the version of `D3.js` SVG. I can go to the link, download it, and customize the SVG. I can then change the link in the `README.md` so it points to this updated SVG and push everything to GitHub. `README.md` does support relative path (ex. `<img src="./logo.svg"`) so this should be fine.

As for making dark mode, I can open an issue and see the community's thoughts on this. We don't want to make the repo larger than it needs to be but if enough people want dark-mode compatible SVGs, we can consider it.

**Comment by Thomas-Boi** [comment]
Please check out #977 and let us know what you think. The more people support the feature, the more likely we will adopt it.

**Comment by WolfgangVing** [comment]
@Thomas-Boi Thank you for your comprehension of the topic, also thank you for going out of your way and showing a way to of solution. I appreciate it.
