### ISSUE TITLE
[FEATURE REQUEST] Update the CONTRIBUTING.md

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#978]
### Problem

Our current `CONTRIBUTING.md` is quite verbose. I'm thinking it could use some more pictures/images or even a new layout. This'll help new contributors to start contributing to our repo and not shy away from issues.

### Suggested feature

Perhaps changing the file from a Markdown file to a HTML file would be a better idea? We could even link to it from our current website.

Besides that, these changes are necessary as well:
- Review and improve instructions in the docs
- Add more images

### Additional information

I'm interested in doing this. I'm thinking vanilla HTML, CSS and JS should be enough since there's not a lot of functionality required. Are there any templating library or framework that can make this easier?

**Comment by maltejur** [comment]
I don't think that markdown is the problem, I think the problem is that all of the information is stored (relatively unstructured) in one single file.

I would suggest creating a github wiki and having multiple pages. For example, you could put the current `What Icons Do We Accept?` heading and similar ones on their own pages. Then you could have the "main" page which roughly explains the steps for creating a new icon and in those steps links to the other pages, like `SVG Standards` or `Versions and Naming Conventions`.

**Comment by Thomas-Boi** [comment]
@maltejur that's a great idea. I agree, the only issue is that we have all the information in one file. I'll look into GitHub wikis and see if we can make one

**Comment by Thomas-Boi** [comment]
The wikis seem like a great fit for what I'm trying to do. Thanks @maltejur. I'll work on this within the next few weeks

**Comment by Panquesito7** [comment]
Great discussion and ideas 🚀 Let me know if you need any help!
